#!/usr/bin/env bash
# Existing-node discovery mode: report redacted current state; never rotate secrets.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=lib/pool-ledger-layout.sh
source "${REPO_ROOT}/deploy/scripts/lib/pool-ledger-layout.sh"

WRITE_REPORT=0
REPORT_PATH="${REPO_ROOT}/docs/runbooks/generated/sc-node-current-state-redacted.md"

usage() {
  cat <<'EOF'
Usage: discover-sc-node-current-state.sh [--write-report]

Existing-node discovery mode:
- validate pool-ledger layout and permissions
- redact/summarize env files and systemd EnvironmentFile paths
- run DATABASE_URL smoke test as azledger (never prints DATABASE_URL)
- never rotate or overwrite secrets
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --write-report)
      WRITE_REPORT=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

emit_section() {
  printf '%s\n' "$@"
}

report() {
  emit_section "# SC-node current state (redacted)"
  emit_section ""
  emit_section "Generated by \`deploy/scripts/discover-sc-node-current-state.sh\` — secrets redacted."
  emit_section ""
  emit_section "## Pool-ledger layout"
  emit_section ""
  emit_section '```'
  pool_ledger_file_stat_summary "${POOL_LEDGER_DIR}" || true
  pool_ledger_validate_dir_layout || true
  emit_section '```'
  emit_section ""
  emit_section "| File | Expected |"
  emit_section "|------|----------|"
  emit_section "| \`${COLLECTOR_ENV}\` | root:azledger 0640 |"
  emit_section "| \`${FRESH_CYCLE_ENV}\` | root:azledger 0640 |"
  emit_section "| \`${SCHEDULER_ENV}\` | root:azledger 0660 |"
  emit_section ""
  for f in "${COLLECTOR_ENV}" "${FRESH_CYCLE_ENV}" "${SCHEDULER_ENV}"; do
    emit_section "### ${f}"
    emit_section '```'
    pool_ledger_validate_env_file "${f}" "$( [[ "${f}" == "${SCHEDULER_ENV}" ]] && echo 0660 || echo 0640 )"
    pool_ledger_redact_file "${f}"
    emit_section '```'
    emit_section ""
  done
  emit_section "## Secret source map"
  emit_section ""
  emit_section "| Concern | Path |"
  emit_section "|---------|------|"
  emit_section "| AZCoin RPC auth | /etc/azcoin/azcoin.conf |"
  emit_section "| Ledger DB | ${COLLECTOR_ENV} |"
  emit_section "| Fresh-cycle policy | ${FRESH_CYCLE_ENV} |"
  emit_section "| Payout scheduler mode | ${SCHEDULER_ENV} |"
  emit_section "| WireGuard keys | /etc/wireguard/keys/ |"
  emit_section ""
  emit_section "## Fresh-cycle execute-live posture"
  emit_section '```'
  pool_ledger_report_execute_live_configured
  emit_section '```'
  emit_section ""
  emit_section "## Systemd services"
  emit_section ""
  for svc in \
    azcoind.service \
    azcoin-template-provider.service \
    azcoin-pool-collector.service \
    azcoin-sc-node-fresh-cycle-automation.service \
    azcoin-sc-node-payout-scheduler.service \
    pool-sv2.service
  do
    emit_section "### ${svc}"
    emit_section "- enabled: $(systemctl is-enabled "${svc}" 2>/dev/null || echo unknown)"
    emit_section "- active: $(systemctl is-active "${svc}" 2>/dev/null || echo unknown)"
    emit_section "- EnvironmentFile:"
    while IFS= read -r ef; do
      [[ -n "${ef}" ]] && emit_section "  - ${ef}"
    done < <(pool_ledger_systemd_environment_files "${svc}")
    emit_section ""
  done
  emit_section "## DATABASE_URL smoke test"
  emit_section '```'
  pool_ledger_db_smoke_test || emit_section "DB smoke test: FAILED"
  emit_section '```'
}

if [[ "${WRITE_REPORT}" -eq 1 ]]; then
  install -d -o root -g root -m 0755 "$(dirname "${REPORT_PATH}")" 2>/dev/null || mkdir -p "$(dirname "${REPORT_PATH}")"
  report | tee "${REPORT_PATH}"
  echo "REPORT_OK path=${REPORT_PATH}"
else
  report
fi
